
name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:11.1-rc
        ports:
          - 3306
        env:
          MYSQL_USER: user
          MYSQL_PASSWORD: password
          MYSQL_DATABASE: test
          MYSQL_ROOT_PASSWORD: password
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 1.16
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
      - name: Setup Selenium Webdriver
        uses: nanasess/setup-chromedriver@v1
      - name: Setup Selenium Webdriver settings
        run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
      - name: Verify MariaDB connection
        env:
          PORT: ${{ job.services.mariadb.ports[3306] }}
        run: |
          while ! mysqladmin ping -h"127.0.0.1" -P"$PORT" --silent; do
            sleep 1
          done
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Build with Gradle
        env:
          MYSQL_DB: test
          MYSQL_USER: user
          MYSQL_PASS: password
          MYSQL_PORT: ${{ job.services.mariadb.ports[3306] }}
          CHROMEDRIVER: /usr/local/bin/chromedriver
        run: |
          cd Plan
          ./gradlew build
      - name: tree
        run: tree
      - name: Upload Plan.jar 
        uses: actions/upload-artifact@v3
        with:
          name: Plan.jar
          path: builds/*.jar
